# Generated by Django 2.2 on 2019-05-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200)),
                ('CustomerCode', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractCode', models.CharField(max_length=200)),
                ('ContractAttachment', models.CharField(max_length=200)),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('ContractAttachment', models.CharField(max_length=200)),
                ('ContractID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Contracts')),
            ],
        ),
    ]
