# Generated by Django 2.2 on 2019-05-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdetails',
            name='ContractID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='CustomerID',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ContractDetails',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
