# Generated by Django 2.2 on 2019-05-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_auto_20190529_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('SupportStartTime', models.DateTimeField()),
                ('SupportEndTime', models.DateTimeField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=200)),
                ('CustomerCode', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductFeatureName', models.CharField(max_length=200)),
                ('ProductFeatureCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductVersionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductFeatures')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductVersionCode', models.IntegerField()),
                ('ReleaseDate', models.DateTimeField()),
                ('Description', models.TextField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductSuiteName', models.CharField(max_length=200)),
                ('ProductSuiteCode', models.CharField(max_length=200)),
                ('ProductVersionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductVersion')),
            ],
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OnlineCheck', models.BooleanField()),
                ('ProductSuitID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductSuites')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LicenseType', models.CharField(choices=[('1', 'type1'), ('2', 'type2'), ('3', 'type3')], default='1', max_length=1)),
                ('Key', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='1', max_length=1)),
                ('ContractDetailID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ContractDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContractCode', models.CharField(max_length=200)),
                ('ContractAttachment', models.TextField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='ContractID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Contracts'),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='ProductBundleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductBundle'),
        ),
        migrations.CreateModel(
            name='ActiveFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeatureID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductFeatures')),
                ('ProductSuiteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductSuites')),
            ],
        ),
    ]
