# Generated by Django 2.2 on 2019-06-01 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190529_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdetails',
            name='ContractID',
        ),
        migrations.RemoveField(
            model_name='contractdetails',
            name='ProductBundleID',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='licensekeys',
            name='ContractDetailID',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='ProductSuitID',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='productsuites',
            name='ProductVersionID',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='productversiondetails',
            name='ProductVersionID',
        ),
        migrations.DeleteModel(
            name='ActiveFeatures',
        ),
        migrations.DeleteModel(
            name='ContractDetails',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='LicenseKeys',
        ),
        migrations.DeleteModel(
            name='ProductBundle',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductSuites',
        ),
        migrations.DeleteModel(
            name='ProductVersion',
        ),
        migrations.DeleteModel(
            name='ProductVersionDetails',
        ),
    ]
