# Generated by Django 2.2 on 2019-06-02 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activefeatures',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='activefeatures',
            name='product_suite_id',
        ),
        migrations.RemoveField(
            model_name='contractdetails',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='contractdetails',
            name='product_bundle_id',
        ),
        migrations.RemoveField(
            model_name='contracts',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='licensekeys',
            name='contract_detail_id',
        ),
        migrations.RemoveField(
            model_name='productbundle',
            name='product_suit_id',
        ),
        migrations.RemoveField(
            model_name='productfeatures',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productsuites',
            name='product_version_id',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='productversiondetails',
            name='product_version_id',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='ActiveFeatures',
        ),
        migrations.DeleteModel(
            name='ContractDetails',
        ),
        migrations.DeleteModel(
            name='Contracts',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='LicenseKeys',
        ),
        migrations.DeleteModel(
            name='ProductBundle',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='ProductSuites',
        ),
        migrations.DeleteModel(
            name='ProductVersion',
        ),
        migrations.DeleteModel(
            name='ProductVersionDetails',
        ),
    ]
