# Generated by Django 2.2 on 2019-06-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20190602_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetails',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='support_end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='support_start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='release_date',
            field=models.DateField(),
        ),
    ]
