# Generated by Django 2.2 on 2019-06-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0010_auto_20190602_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('support_start_time', models.DateField()),
                ('support_end_time', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_code', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_feature_name', models.CharField(max_length=200)),
                ('product_feature_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductFeatures')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_version_code', models.IntegerField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_suite_name', models.CharField(max_length=200)),
                ('product_suite_code', models.CharField(max_length=200)),
                ('product_version_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductVersionDetails')),
            ],
        ),
        migrations.AddField(
            model_name='productfeatures',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Products'),
        ),
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurrent_user_count', models.IntegerField()),
                ('online_check', models.BooleanField()),
                ('product_suit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductSuites')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('1', 'type1'), ('2', 'type2'), ('3', 'type3')], default='1', max_length=1)),
                ('key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('1', 'active'), ('0', 'inactive')], default='1', max_length=1)),
                ('contract_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ContractDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_code', models.CharField(max_length=200)),
                ('contract_attachment', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Customers')),
            ],
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Contracts'),
        ),
        migrations.AddField(
            model_name='contractdetails',
            name='product_bundle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductBundle'),
        ),
        migrations.CreateModel(
            name='ActiveFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductFeatures')),
                ('product_suite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductSuites')),
            ],
        ),
    ]
